language: python
addons:
  apt:
    packages:
      - openjdk-8-jdk
matrix:
  include:
    - python: "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - py.test --cov=py_hiverunner tests
after_success:
  - codecov